### ISSUE TITLE
Changes to homu config encounter salt error

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#1010]
The "salt from upgrade" CI job fails:
```
----------

          ID: homu

    Function: pip.installed

      Result: False

     Comment: An exception occurred in this state: Traceback (most recent call last):

                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call

                  **cdata['kwargs'])

                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1951, in wrapper

                  return f(*args, **kwargs)

                File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 812, in installed

                  **kwargs)

                File "/usr/lib/python2.7/dist-packages/salt/states/pip_state.py", line 314, in _check_if_installed

                  for version in reversed(available_versions):

              TypeError: argument to reversed() must be a sequence

     Started: 22:51:27.656454

    Duration: 1829.83 ms

     Changes:   
```

**Comment by jdm** [comment]
This is preventing merging #1007 right now.

**Comment by jdm** [comment]
Attempting to investigate in https://github.com/servo/saltfs/compare/master...jdm-patch-72?quick_pull=1.
