### ISSUE TITLE
Ensure that reprovisioning Linux clients updates setuptools

### ISSUE THREAD

**Issue by larsbergstrom** [servo/saltfs#475]
We were getting:
```
Pip failed to execute properly:
Output: 
Error: Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/home/servo/buildbot/slave/arm64/build/python/_virtualenv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 372, in setup_py
    import setuptools  # noqa
  File "/home/servo/buildbot/slave/arm64/build/python/_virtualenv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 13, in <module>
    from setuptools.extension import Extension
  File "/home/servo/buildbot/slave/arm64/build/python/_virtualenv/local/lib/python2.7/site-packages/setuptools/extension.py", line 9, in <module>
    from .monkey import get_unpatched
  File "/home/servo/buildbot/slave/arm64/build/python/_virtualenv/local/lib/python2.7/site-packages/setuptools/monkey.py", line 10, in <module>
    from . import msvc
  File "/home/servo/buildbot/slave/arm64/build/python/_virtualenv/local/lib/python2.7/site-packages/setuptools/msvc.py", line 27, in <module>
    from . import monkey
ImportError: cannot import name monkey


program finished with exit code 1
elapsedTime=2.401514
```

Which was due to a broken (recursive deps) setuptools:
https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v2712

I was a Bad Admin and just logged in and did a bunch of:
```
pip install --upgrade setuptools
```

But we should do the right thing here and make sure we properly are updating setuptools.

**Comment by larsbergstrom** [comment]
That step resulted in:
```
root@MACHINE:~# pip install --upgrade setuptools
Downloading/unpacking setuptools from https://pypi.python.org/packages/2d/76/bce013588c82099ea243241441364db1e55a8d2d1a7cc962cee8873ccaea/setuptools-27.1.2-py2.py3-none-any.whl#md5=5f5be1c83ef30979bb1bf0ed3cb2b417
  Downloading setuptools-27.1.2-py2.py3-none-any.whl (464kB): 464kB downloaded
Installing collected packages: setuptools
  Found existing installation: setuptools 3.3
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed setuptools
Cleaning up...
```
