### ISSUE TITLE
Discussion: Should we upgrade pip more aggressively?

### ISSUE THREAD

**Issue by edunham** [servo/saltfs#654]
servo-linux3 got into a bad state and needed its android dir blown away and replaced by a highstate today. That's fine. What's not fine is that the highstate didn't work until after I ran `pip install --upgrade pip` on the host. 

Error from Salt before upgrading Pip:
```
----------
          ID: virtualenv
    Function: pip.installed
      Result: False
     Comment: Error installing 'virtualenv == 14.0.6': Exception:
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
                  status = self.run(options, args)
                File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 74, in run
                  req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
                File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 286, in from_dist
                  assert len(specs) == 1 and specs[0][0] == '=='
              AssertionError
              
              Storing debug log for failure in /root/.pip/pip.log
     Started: 20:14:15.620240
    Duration: 256.634 ms
     Changes:   
----------
          ID: buildbot-slave-dependencies
    Function: pip.installed
      Result: False
     Comment: Error installing 'buildbot-slave == 0.8.12': Exception:
              Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
                  status = self.run(options, args)
                File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 74, in run
                  req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
                File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 286, in from_dist
                  assert len(specs) == 1 and specs[0][0] == '=='
              AssertionError
              
              Storing debug log for failure in /root/.pip/pip.log
     Started: 20:14:15.877244
    Duration: 254.463 ms
     Changes:   
```

Contents of logfile on linux3: 

```
root@(servo-linux3):~# cat /root/.pip/pip.log 
------------------------------------------------------------
/usr/bin/pip2 run on Thu May  4 20:14:16 2017
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/freeze.py", line 74, in run
    req = pip.FrozenRequirement.from_dist(dist, dependency_links, find_tags=find_tags)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 286, in from_dist
    assert len(specs) == 1 and specs[0][0] == '=='
AssertionError
```

What happened when I asked the host nicely to fix its Pip:

```
root@(servo-linux3):~# pip install --upgrade pip
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.4
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed pip
Cleaning up...
```

And after that a highstate of the host was fine. 

Since we often run a highstate to retrieve the host from an arbitrarily broken configuration, I think it couldn't hurt and could sometimes help to explicitly upgrade pip at the start of a highstate. However, I can see how this could be a Salt code smell, as it will sometimes be a no-op. 

@aneeshusa, what's the best practice here?

**Comment by aneeshusa** [comment]
The root cause of the pip error is that the pip shipped in the Ubuntu package `python-pip` is version 1.5.4, which is rather old (released 2014-02-21!). It seems to choke when running `pip freeze`, possibly depending on which Python modules are installed. Ideally these kinds of problems will go away when we update to a more recent OS (Ubuntu 16.04).

The solution, as you've found, is to install a new pip via pip. The new pip ends up in `/usr/local/lib/python2.7'; the first pip can either the original, old pip from the `python-pip` apt package that lives in `/usr/lib/python2.7`, or the new pip itself. IMO we should pin pip to a known good version (see also #601). I see two approaches here:
- Use a `pip.installed` state, which will handle the version for us.
- Use a `cmd.run` state, including an `unless` argument so the command is only actually executed if the current pip version doesn't match the version we want to pin.

The pip in `python-pip` is fairly old, so I think the second approach is safer as we can scope it to a safe subset of pip commands, as opposed to `pip.installed` which calls pip in a lot of different ways. We can use Salt requisites and other ordering control mechanisms to ensure this is run before other Python related states when highstating. @edunham if you can find a way to easily reproduce this failure locally, I can put together + test a PR for this.
