### ISSUE TITLE
servo-mac7 can't complete git checkout

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#680]
We've seen this consistently in servo/servo#17042:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/buildbot/process/buildstep.py", line 322, in startStep
    result = yield self.run()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1445, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/home/servo/buildbot/master/factories.py", line 40, in run
    got_rev, rev
exceptions.Exception: Actual commit (8daa4ef070f0996b482a96e04bc86ecc21f7efcd) differs from requested commit (1a719a103ea452ba1a1645b0bea93cb8dfcf16e9)
```

**Comment by nox** [comment]
@jdm This happens when we stop builds by hand in Buildbot, lock files don't get cleaned.

**Comment by nox** [comment]
@jdm `servo-mac4` to has the issue, for the `mac-rel-wpt2` job too.

**Comment by nox** [comment]
@jdm See this error, during the Git step:

```
fatal: Unable to create '/Users/servo/buildbot/slave/mac-rel-wpt1/build/.git/index.lock': File exists.
```

**Comment by larsbergstrom** [comment]
This should be fixed now. I basically logged into all of them and did a:
```
find . -name index.lock
```
Then purged any such build directory.

As user `servo` in the `buildbot` directory. Discovered a few additional ones we hadn't hit yet and cleaned them up.

cc @edunham @aneeshusa
