### ISSUE TITLE
Intermittent tracker server does not appear to be running

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#834]
Based on https://github.com/servo/servo/issues/20763.

**Comment by jdm** [comment]
It's failing on startup to read the JSON file:
```
servo@servo-master1:~/intermittent-failure-tracker$ exec /home/servo/intermittent-failure-tracker/_venv/bin/intermittent_failure_tracker
Traceback (most recent call last):
  File "/home/servo/intermittent-failure-tracker/_venv/bin/intermittent_failure_tracker", line 11, in <module>
    load_entry_point('intermittent-failure-tracker==0.1.0', 'console_scripts', 'intermittent_failure_tracker')()
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/intermittent_failure_tracker/flask_server.py", line 57, in <module>
    db = IntermittentsDB("intermittent_errors.json")
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/intermittent_failure_tracker/db.py", line 20, in __init__
    self.db = TinyDB(filename)
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/tinydb/database.py", line 153, in __init__
    self._table = self.table(default_table)
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/tinydb/database.py", line 172, in table
    table = table_class(StorageProxy(self._storage, name), name, **options)
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/tinydb/database.py", line 269, in __init__
    data = self._read()
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/tinydb/database.py", line 359, in _read
    return self._storage.read()
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/tinydb/database.py", line 81, in read
    raw_data = self._storage.read() or {}
  File "/home/servo/intermittent-failure-tracker/_venv/lib/python3.4/site-packages/tinydb/storages.py", line 106, in read
    return json.load(self._handle)
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 346, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 10004243 - line 1 column 20008495 (char 10004242 - 20008494)
```

**Comment by jdm** [comment]
The file contains at least one duplicate copy of the file contents. This seems like a terrifying race somehow; I'm going to fix it by deleting the entire contents because my file editing tools can't handle a 20mb JSON blob.

**Comment by jdm** [comment]
Fixed by removing the file.
