### ISSUE TITLE
servo-linux5 often has OOM errors

### ISSUE THREAD

**Issue by jdm** [servo/saltfs#884]
Eg:
```
error in RunProcess._startCommand
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/buildslave/runprocess.py", line 426, in start
    self._startCommand()
  File "/usr/local/lib/python2.7/dist-packages/buildslave/runprocess.py", line 550, in _startCommand
    usePTY=self.usePTY)
  File "/usr/local/lib/python2.7/dist-packages/buildslave/runprocess.py", line 572, in _spawnProcess
    processProtocol, uid, gid, childFDs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 728, in __init__
    self._fork(path, uid, gid, executable, args, environment, fdmap=fdmap)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/process.py", line 405, in _fork
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by jdm** [comment]
I have restarted the machine.
